### ISSUE TITLE
Attribute should implements Comparable.

### ISSUE THREAD

**Issue by AlainWoeffray** [cloudio-project/cloudio-endpoint-java#14]
To can be used as a map's key, the Attribute class needs to implements Comparable.

```
Exception in thread "Thread-5" java.lang.ClassCastException: 
ch.hevs.cloudio.endpoint.Attribute cannot be cast to java.lang.Comparable
```

**Comment by cm0x4D** [comment]
It would be possible to implement that interface using the UUID of the attribute. But it seems to me that it is a quite unusual use case to use an Attribute as a key for a map. If you create a TreeMap for example, you can pass a Comparator object to the constructor that uses the UUID of the attribute and the Attribute itself does not need to implement the Comparable interface.
