### ISSUE TITLE
Static attribute not in MongoDB.

### ISSUE THREAD

**Issue by AlainWoeffray** [cloudio-project/cloudio-endpoint-java#20]
On the establishment of a connection, I can catch the following message on RabbitMQ at the routing key @online.Development2.

{"nodes":{"TemperatureChamber":{"objects":{"T1":{"objects":{"Telecom":{"attributes":{"RSSI":{"type":"Number","constraint":"Status"}}},"Temperature":{"attributes":{"MeasuredValue":{"type":"Number","constraint":"Status"}}}}}}},"Lamp":{"objects":{"L1":{"attributes":{"IsOn":{"type":"Boolean","constraint":"Status"},"RSSI":{"type":"Number","constraint":"Status"},"OffAction":{"type":"Boolean","constraint":"SetPoint"}}}}},"Admin":{"objects":{"Metadata":{"attributes":{**"Version":{"type":"String","constraint":"Static","value":"0.2.toto"}**}},"Mode":{"attributes":{"Live":{"type":"Boolean","constraint":"SetPoint"}}},"Telegram":{"attributes":{"RX":{"type":"String","constraint":"Status"},"TX":{"type":"String","constraint":"SetPoint"}}},"Config":{"attributes":{"Set":{"type":"String","constraint":"SetPoint"},"Get":{"type":"String","constraint":"Status"},"Status":{"type":"String","constraint":"Status"},"ErrorMessage":{"type":"String","constraint":"Status"}}},"Command":{"attributes":{"Action":{"type":"String","constraint":"SetPoint"}}}}}}}

But, there is no "Version" attribute on the MongoDB. In facts, there is even no nodes called "Admin".

**Comment by cm0x4D** [comment]
It is not a bug of the endpoint library, it seems to be rather on the server implementation, I leave it here as there is currently no repo for the server implementation.

**Comment by cm0x4D** [comment]
https://github.com/cloudio-project/cloudio-cloud-backend-mongo-influx/issues/1
